export const mockData={
  "Unallocated": [
    {
      "Date & Time": "2024",
      "Ticket No": "123456",
      "Jobsheet No": "JS123456",
      "Model": "ModelA",
      "Defect": "Screen issue",
      "Bin": "A1",
      "Tray No": "T1",
      "Assigned To": "Technician1",
    },
    {
      "Date & Time": "2024",
      "Ticket No": "123457",
      "Jobsheet No": "JS123457",
      "Model": "ModelB",
      "Defect": "Battery issue",
      "Bin": "B2",
      "Tray No": "T2",
      "Assigned To": "Technician2",
    },
    {
      "Date & Time": "2024",
      "Ticket No": "123456",
      "Jobsheet No": "JS123456",
      "Model": "ModelA",
      "Defect": "Charging issue",
      "Bin": "A1",
      "Tray No": "T1",
      "Assigned To": "Techn 2",
    },
    {
      "Date & Time": "2024",
      "Ticket No": "123456",
      "Jobsheet No": "JS123456",
      "Model": "ModelA",
      "Defect": "Display issue",
      "Bin": "A1",
      "Tray No": "T1",
      "Assigned To": "Techn 9",
    },
    {
      "Date & Time": "2024",
      "Ticket No": "123456",
      "Jobsheet No": "JS123456",
      "Model": "ModelA",
      "Defect": "Brigntness issue",
      "Bin": "A1",
      "Tray No": "T1",
      "Assigned To": "Techn 1",
    },
    {
      "Date & Time": "2024",
      "Ticket No": "123456",
      "Jobsheet No": "JS123456",
      "Model": "ModelA",
      "Defect": "Screen issue",
      "Bin": "A1",
      "Tray No": "T1",
      "Assigned To": "Technician1",
    },
    {
      "Date & Time": "2024",
      "Ticket No": "123456",
      "Jobsheet No": "JS123456",
      "Model": "ModelA",
      "Defect": "display issue",
      "Bin": "A1",
      "Tray No": "T1",
      "Assigned To": "Technician1",
    },
    {
      "Date & Time": "2024",
      "Ticket No": "123456",
      "Jobsheet No": "JS123456",
      "Model": "ModelA",
      "Defect": "display issue",
      "Bin": "A1",
      "Tray No": "T1",
      "Assigned To": "Technician1",
    },
    {
      "Date & Time": "2024",
      "Ticket No": "123456",
      "Jobsheet No": "JS123456",
      "Model": "ModelA",
      "Defect": "display issue",
      "Bin": "A1",
      "Tray No": "T1",
      "Assigned To": "Technician1",
    },
    {
      "Date & Time": "2024",
      "Ticket No": "123456",
      "Jobsheet No": "JS123456",
      "Model": "ModelA",
      "Defect": "Screen issue",
      "Bin": "A1",
      "Tray No": "T1",
      "Assigned To": "Technician1",
    },
  ],
  "Allocated": [
      {
        "Date & Time": "2024",
        "Ticket No": "123456",
        "Jobsheet No": "JS123456",
        "Model": "ModelA",
        "Defect": "Screen not working",
        "Bin": "A1",
        "Tray No": "T1",
        "Assigned To": "Technician1",
        
      },
      {
        "Date & Time": "2024",
        "Ticket No": "123457",
        "Jobsheet No": "JS123457",
        "Model": "ModelB",
        "Defect": "Battery issue",
        "Bin": "B2",
        "Tray No": "T2",
        "Assigned To": "Technician2",
       
      }
    ],
  "Reappointment": [
      {
        "Date & Time": "2024",
        "Ticket No": "123458",
        "Jobsheet No": "JS123458",
        "Model": "ModelC",
        "Defect": "Software issue",
        "Bin": "C3",
        "Tray No": "T3",
        "Assigned To": "Technician3",
      },
      {
        
        "Date & Time": "2024",
        "Ticket No": "123459",
        "Jobsheet No": "JS123459",
        "Model": "ModelD",
        "Defect": "Camera malfunction",
        "Bin": "D4",
        "Tray No": "T4",
        "Assigned To": "Techn 4",
      },
      {
        "Date & Time": "2024",
        "Ticket No": "123458",
        "Jobsheet No": "JS123458",
        "Model": "ModelC",
        "Defect": "Software issue",
        "Bin": "C3",
        "Tray No": "T3",
        "Assigned To": "Technician3",
      },
      {
        "Date & Time": "2024",
        "Ticket No": "123458",
        "Jobsheet No": "JS123458",
        "Model": "ModelC",
        "Defect": "Software issue",
        "Bin": "C3",
        "Tray No": "T3",
        "Assigned To": "Technician3",
      },
      {
        "Date & Time": "2024",
        "Ticket No": "123458",
        "Jobsheet No": "JS123458",
        "Model": "ModelC",
        "Defect": "Software issue",
        "Bin": "C3",
        "Tray No": "T3",
        "Assigned To": "Technician3",
      },
      {
        "Date & Time": "2024",
        "Ticket No": "123458",
        "Jobsheet No": "JS123458",
        "Model": "ModelC",
        "Defect": "Software issue",
        "Bin": "C3",
        "Tray No": "T3",
        "Assigned To": "Technician3",
      },
    ],
  "Pending Part": [
      {
        "Date & Time": "2025",
        "Ticket No": "123460",
        "Jobsheet No": "JS123460",
        "Model": "ModelE",
        "Defect": "Speaker issue",
        "Bin": "E5",
        "Tray No": "T5",
        "Assigned To": "Techni 5",
      },
      {
        "Date & Time": "2024",
        "Ticket No": "123461",
        "Jobsheet No": "JS123461",
        "Model": "ModelF",
        "Defect": "Power button broken",
        "Bin": "F6",
        "Tray No": "T6",
        "Assigned To": "Technician6",
       
      }
    ],
   "Closed": [
      {
        
        "Date & Time": "2024",
        "Ticket No": "123462",
        "Jobsheet No": "JS123462",
        "Model": "ModelG",
        "Defect": "Charging issue",
        "Bin": "G7",
        "Tray No": "T7",
        "Assigned To": "Technician7",
    
      },
      {
        
        "Date & Time": "2024",
        "Ticket No": "123463",
        "Jobsheet No": "JS123463",
        "Model": "ModelH",
        "Defect": "Display problem",
        "Bin": "H8",
        "Tray No": "T8",
        "Assigned To": "Technician8",
      
      }
    ]
  }
  